"""add assets and asset_ports tables

Revision ID: 38ec4aadd5d9
Revises: 1bd187c0178c
Create Date: 2026-05-19 11:02:26.349486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ec4aadd5d9'
down_revision: Union[str, None] = '1bd187c0178c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_no', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('os_info', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('business_system', sa.String(length=100), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('network_zone', sa.String(length=20), nullable=False),
    sa.Column('cpu', sa.String(length=100), nullable=True),
    sa.Column('memory_gb', sa.Integer(), nullable=True),
    sa.Column('disk_gb', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.String(length=20), nullable=True),
    sa.Column('warranty_expiry', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('last_scan_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("asset_type IN ('physical', 'virtual', 'network_device', 'other')", name='ck_assets_type'),
    sa.CheckConstraint("importance IN ('core', 'important', 'normal')", name='ck_assets_importance'),
    sa.CheckConstraint("network_zone IN ('dmz', 'intranet', 'office', 'management', 'other')", name='ck_assets_zone'),
    sa.CheckConstraint("source IN ('scan', 'manual')", name='ck_assets_source'),
    sa.CheckConstraint("status IN ('online', 'offline', 'decommissioned')", name='ck_assets_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_no')
    )
    op.create_index('idx_assets_ip', 'assets', ['ip_address'], unique=False)
    op.create_index('idx_assets_mac', 'assets', ['mac_address'], unique=False)
    op.create_index('idx_assets_status', 'assets', ['status'], unique=False)
    op.create_index('idx_assets_zone', 'assets', ['network_zone'], unique=False)
    op.create_table('asset_ports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=True),
    sa.Column('service_version', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'port_number', 'protocol', name='uq_asset_port_proto')
    )
    op.create_index('idx_ports_asset', 'asset_ports', ['asset_id'], unique=False)
    op.create_index('idx_ports_number', 'asset_ports', ['port_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ports_number', table_name='asset_ports')
    op.drop_index('idx_ports_asset', table_name='asset_ports')
    op.drop_table('asset_ports')
    op.drop_index('idx_assets_zone', table_name='assets')
    op.drop_index('idx_assets_status', table_name='assets')
    op.drop_index('idx_assets_mac', table_name='assets')
    op.drop_index('idx_assets_ip', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
