"""add scan_batches and scan_snapshot_items

Revision ID: e1900e881739
Revises: 38ec4aadd5d9
Create Date: 2026-05-19 11:15:22.652289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1900e881739'
down_revision: Union[str, None] = '38ec4aadd5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('scan_started_at', sa.DateTime(), nullable=True),
    sa.Column('scan_finished_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('total_hosts', sa.Integer(), nullable=True),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('changed_count', sa.Integer(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_snapshot_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_batch_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('os_info', sa.String(length=255), nullable=True),
    sa.Column('port_number', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('service_name', sa.String(length=50), nullable=True),
    sa.Column('service_version', sa.String(length=255), nullable=True),
    sa.Column('matched_asset_id', sa.Integer(), nullable=True),
    sa.Column('diff_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['matched_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['scan_batch_id'], ['scan_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_snapshot_items')
    op.drop_table('scan_batches')
    # ### end Alembic commands ###
